// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxybdckcmeusxcwzourw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94eWJkY2tjbWV1c3hjd3pvdXJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NzA0NTIsImV4cCI6MjA2NzE0NjQ1Mn0.st3PWlzYwXzlRE5OV1UCfIMvHJEi6YPiBGMYwVoPD70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});